service:
  server:
    port: 9000
    path: /
    root_directory: /home/$whoami/.lenscast
  log:
    path: ./log
  slideshow:
    image:
      duration: 7 # seconds
    video:
      autoplay: 1 # 0 == off // 1 == on
