#!/bin/sh
#
# Copy feather icons from node_modules to vendor directory

mkdir -p public/vendor/
cp -r node_modules/feather-icons/dist/ public/vendor/feather-icons

printf '%s\n' "Setup feather icons"
